### ISSUE TITLE
{"captcha_key": ["You need to update your app to join this server."]

### ISSUE THREAD

**Issue by BLAMEITONBRADEN** [kittiescaties/discord-mass-token-joiner#1]
{"captcha_key": ["You need to update your app to join this server."]

**Comment by kittiescaties** [comment]
this means token has gotten a captcha

**Comment by BLAMEITONBRADEN** [comment]
are you able to add a capmonster thing or anti captcha

**Comment by kittiescaties** [comment]
I will add when I have time as I am working on another project

**Comment by anilsoylu** [comment]
I am getting error 10008. what is the solution to this?
